
import numpy

from apgl.graph import *
from apgl.generator.ErdosRenyiGenerator import ErdosRenyiGenerator
from apgl.util.Util import Util 

class BoundGraphIterator(object): 
    """
    Take 3 clusters generated by Erdos Renyi processes and then add random edges 
    successively to model "noise". 
    """
    def __init__(self, changeEdges=10, numGraphs=100, numClusterVertices=50, p=0.3): 
        self.changeEdges = changeEdges 
        self.numGraphs = numGraphs
        self.graphInd = 0
        generator = ErdosRenyiGenerator(p)
        
        graph1 = SparseGraph(GeneralVertexList(numClusterVertices))
        
        graph1 = generator.generate(graph1)
        print(graph1)
        
        graph2 = SparseGraph(GeneralVertexList(numClusterVertices))
        graph2 = generator.generate(graph2)
        
        graph3 = SparseGraph(GeneralVertexList(numClusterVertices))
        graph3 = generator.generate(graph3)
        
        graph = graph1.concat(graph2).concat(graph3) 
        self.graph = graph 
        
        self.realClustering = numpy.zeros(numClusterVertices*3)
        self.realClustering[numClusterVertices:2*numClusterVertices] = 1 
        self.realClustering[numClusterVertices*2:] = 2 
        
    def __iter__(self):
        return self
        
    def next(self):
        if self.graphInd == self.numGraphs: 
            raise StopIteration
        
        i = 0
        while i < self.changeEdges: 
            inds = numpy.random.randint(0, self.graph.size, 2)
            if self.graph[inds[0], inds[1]] == 0: 
                self.graph[inds[0], inds[1]] = 1
                i += 1 
        
        #logging.debug(self.graph)        
        
        W = self.graph.getSparseWeightMatrix().tocsr()
        self.graphInd += 1 
        return W 
            